### ISSUE TITLE
Audio libraries

### ISSUE THREAD

**Issue by jukkae** [HelsinginSahko/mossman#3]
Look into audio libraries.
Possible options:
- CLAM http://clam-project.org/
- PortAudio http://www.portaudio.com/
- ESSENTIA http://essentia.upf.edu/
- SFML audio features?
- MARF http://marf.sourceforge.net/
- Marsyas http://marsyas.info/
- SPKit http://www.helsinki.fi/music/research/spkit/documentation/SPKit.html
- RtAudio http://www.music.mcgill.ca/~gary/rtaudio/
- Roll our own :) What we really need is a robust audio input buffer; the algorithms we can handle on our own.

**Comment by jukkae** [comment]
"RtAudio is a set of C++ classes that provide a common API (Application Programming Interface) for realtime audio input/output across Linux, Macintosh OS-X and Windows operating systems. RtAudio significantly simplifies the process of interacting with computer audio hardware. It was designed with the following objectives:" Sounds pretty good to me.

**Comment by vijoc** [comment]
:+1: for RtAudio

**Comment by jukkae** [comment]
Going for RtAudio right now.
